### ISSUE TITLE
add phptownhall podcast

### ISSUE THREAD

**Issue by matthewtrask** [simon-schubert/devpunk#41]
hey there, Im one of the hosts of PHPTownhall, along with Ben Edmunds. Are you open to the podcast being added to the list?

**Comment by simon-schubert** [comment]
hey matt, thank you! I created a PR: https://github.com/simon-schubert/devpunk/pull/42

could you quickly check, if I got everything right?

**Comment by matthewtrask** [comment]
@simon-schubert looks great!

**Comment by simon-schubert** [comment]
@matthewtrask thank you!
